version: "3.8"
services:
  frontend:
    image: patelparth17/react
    container_name: react
    ports:
      - "3000:3000"
    networks:
      - my-net
    depends_on:
      - spring

  backend:
    image: patelparth17/spring
    container_name: spring
    ports:
      - "9000:9000"
    networks:
      - my-net
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: mysql
    networks:
      - my-net
    environment:
      - MYSQL_ROOT_PASSWORD=P&Nwentupthehi11
      - MYSQL_DATABASE=car_rental
      - MYSQL_USER=parth
      - MYSQL_PASSWORD=P&Nwentupthehi11

networks:
  my-net:
