version: "2.4"
services:

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    networks:
      - my-net
    environment:
      - MYSQL_ROOT_PASSWORD=P&Nwentupthehi11
      - MYSQL_DATABASE=car_rental
      - MYSQL_USER=parth
      - MYSQL_PASSWORD=P&Nwentupthehi11
    volumes:
      - mysql_data_volume:/var/lib/mysql

    ports:
      - "9001:3306"

  react:
    image: patelparth17/react
    container_name: react
    ports:
      - "3000:3000"
    networks:
      - my-net
    depends_on:
      - spring

  spring:
    image: patelparth17/spring
    container_name: spring
    ports:
      - "9000:9000"
    networks:
      - my-net
    depends_on:
      mysql:
        condition: service_healthy


networks:
  my-net:

volumes:
  mysql_data_volume:

