---
- name: Deploying the application
  hosts: all
  tasks:
    - name: Starting the docker service
      service:
        name: docker
        state: started

    - name: Copying the docker compose file
      copy:
        src: ./docker-compose.yml
        dest: ./


#    - name: cleaning the docker compose workspace in the local system
#      shell: docker-compose down

    - name: Starting the application
      shell: docker-compose up -d